In [1]:
!pip install -q transformers datasets accelerate scikit-learn

In [2]:
from datasets import Dataset

data = {
    "text": [
        "I forgot my password",
        "I cannot access my account",
        "I want to update my email address",

        "I was charged twice",
        "Why was my card charged?",
        "The payment amount is incorrect",

        "Where is my order?",
        "My package has not arrived",
        "When will my order be delivered?",

        "I want a refund",
        "How can I return my product?",
        "I need my money back",

        "My app keeps crashing",
        "The website is showing an error",
        "My application is not working"
    ],

    "label": [
        "account", "account", "account",
        "billing", "billing", "billing",
        "delivery", "delivery", "delivery",
        "refund", "refund", "refund",
        "technical", "technical", "technical"
    ]
}

dataset = Dataset.from_dict(data)

print(dataset)

Dataset({
    features: ['text', 'label'],
    num_rows: 15
})

In [3]:
labels = sorted(set(dataset["label"]))

label2id = {
    label: i
    for i, label in enumerate(labels)
}

id2label = {
    i: label
    for label, i in label2id.items()
}

print("Labels:", labels)
print("Label to ID:", label2id)
print("ID to Label:", id2label)

Labels: ['account', 'billing', 'delivery', 'refund', 'technical']
Label to ID: {'account': 0, 'billing': 1, 'delivery': 2, 'refund': 3, 'technical': 4}
ID to Label: {0: 'account', 1: 'billing', 2: 'delivery', 3: 'refund', 4: 'technical'}

In [4]:
def encode_labels(example):
    example["labels"] = label2id[example["label"]]
    return example

dataset = dataset.map(encode_labels)

dataset = dataset.remove_columns(["label"])

print(dataset)

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Dataset({
    features: ['text', 'labels'],
    num_rows: 15
})

In [5]:
dataset = dataset.train_test_split(
    test_size=0.2,
    seed=42
)

print(dataset)

DatasetDict({
    train: Dataset({
        features: ['text', 'labels'],
        num_rows: 12
    })
    test: Dataset({
        features: ['text', 'labels'],
        num_rows: 3
    })
})

In [6]:
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification
)

model_name = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(labels),
    id2label=id2label,
    label2id=label2id
)

print("Model and tokenizer loaded successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model and tokenizer loaded successfully!

In [7]:
def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

tokenized_dataset = dataset.map(
    tokenize_function,
    batched=True
)

print(tokenized_dataset)

Map:   0%|          | 0/12 [00:00<?, ? examples/s]

Map:   0%|          | 0/3 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 12
    })
    test: Dataset({
        features: ['text', 'labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 3
    })
})

In [8]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=1,
    report_to="none"
)

print(training_args)

TrainingArguments(
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_in_order=True,
dataloader_multiprocessing_context=None,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_static_graph=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
enable_jit_checkpoint=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_full_eval=False,
fsdp=None,
fsdp_config=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_num_input_tokens_seen=no,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=2e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=False,
local_rank=-1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=1,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs=None,
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
neftune_noise_alpha=None,
num_train_epochs=3,
optim=OptimizerNames.ADAMW_TORCH_FUSED,
optim_args=None,
optim_target_modules=None,
output_dir=./results,
parallelism_config=None,
per_device_eval_batch_size=4,
per_device_train_batch_size=4,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_steps=500,
save_strategy=SaveStrategy.STEPS,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
trackio_bucket_id=None,
trackio_space_id=None,
trackio_static_space_id=None,
train_sampling_strategy=random,
use_cache=False,
use_cpu=False,
use_liger_kernel=False,
warmup_steps=0,
weight_decay=0.01,
)

In [9]:
import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support
)

def compute_metrics(eval_pred):
    logits, labels_true = eval_pred

    predictions = np.argmax(logits, axis=-1)

    accuracy = accuracy_score(
        labels_true,
        predictions
    )

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels_true,
        predictions,
        average="weighted",
        zero_division=0
    )

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

In [10]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    compute_metrics=compute_metrics
)

print("Trainer ready!")

Trainer ready!

In [11]:
trainer.train()

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

TrainOutput(global_step=9, training_loss=1.5948836273617215, metrics={'train_runtime': 56.1109, 'train_samples_per_second': 0.642, 'train_steps_per_second': 0.16, 'total_flos': 1192270371840.0, 'train_loss': 1.5948836273617215, 'epoch': 3.0})

In [12]:
results = trainer.evaluate()

print(results)

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 1.6183099746704102, 'eval_accuracy': 0.0, 'eval_precision': 0.0, 'eval_recall': 0.0, 'eval_f1': 0.0}

In [13]:
trainer.save_model("./customer_support_model")
tokenizer.save_pretrained("./customer_support_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./customer_support_model/tokenizer_config.json',
 './customer_support_model/tokenizer.json')

In [14]:
from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="./customer_support_model",
    tokenizer="./customer_support_model"
)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [15]:
text = "I was charged twice for my order"

result = classifier(text)

print(result)

[{'label': 'technical', 'score': 0.21564321219921112}]

In [16]:
test_messages = [
    "I cannot log into my account",
    "I was charged twice for the same payment",
    "Where is my package?",
    "I want to get my money back",
    "The mobile app keeps crashing"
]

for message in test_messages:
    result = classifier(message)

    print("Message:", message)
    print("Prediction:", result[0]["label"])
    print("Score:", result[0]["score"])
    print("-" * 50)

Message: I cannot log into my account
Prediction: technical
Score: 0.2214198112487793
--------------------------------------------------
Message: I was charged twice for the same payment
Prediction: technical
Score: 0.2121984362602234
--------------------------------------------------
Message: Where is my package?
Prediction: technical
Score: 0.22177831828594208
--------------------------------------------------
Message: I want to get my money back
Prediction: technical
Score: 0.21878741681575775
--------------------------------------------------
Message: The mobile app keeps crashing
Prediction: technical
Score: 0.2347271591424942
--------------------------------------------------

In [17]:
def predict_ticket(message):
    result = classifier(message)[0]

    label = result["label"]
    score = result["score"]

    print("Customer Message:", message)
    print("Predicted Category:", label)
    print("Confidence:", round(score * 100, 2), "%")


predict_ticket("I forgot my password")

Customer Message: I forgot my password
Predicted Category: technical
Confidence: 21.67 %

In [18]:
!pip install -q streamlit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 80.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 31.2 MB/s eta 0:00:00

In [19]:
%%writefile app.py

import streamlit as st
from transformers import pipeline

# Load our trained model
classifier = pipeline(
    "text-classification",
    model="./customer_support_model",
    tokenizer="./customer_support_model"
)

# Page title
st.title("🎫 Customer Support Ticket Classifier")

st.write("Enter a customer message and the AI will predict its category.")

# Text input
message = st.text_area(
    "Customer Message",
    placeholder="Example: I was charged twice for my payment"
)

# Prediction button
if st.button("Predict"):

    if message.strip() == "":
        st.warning("Please enter a customer message.")

    else:
        result = classifier(message)[0]

        label = result["label"]
        score = result["score"]

        st.success(f"Predicted Category: {label}")
        st.info(f"Confidence: {score * 100:.2f}%")

Writing app.py

In [20]:
!pkill -f streamlit || echo "No previous Streamlit process"

^C

In [21]:
!pip install streamlit -q
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

!pkill streamlit || echo "No previous Streamlit process"
import time, subprocess

streamlit_proc = subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501", "--server.headless", "true"])
time.sleep(8)

# Create tunnel
!cloudflared tunnel --url http://localhost:8501 --no-autoupdate

Selecting previously unselected package cloudflared.
(Reading database ... 122815 files and directories currently installed.)
Preparing to unpack cloudflared-linux-amd64.deb ...
Unpacking cloudflared (2026.10.0) ...
Setting up cloudflared (2026.10.0) ...
Processing triggers for man-db (2.12.0-4build2) ...
No previous Streamlit process
2026-10-06T10:20:53Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-10-06T10:20:53Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-10-06T10:20:56Z INF +--------------------------------------------------------------------------------------------+
2026-10-06T10:20:56Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-10-06T10:20:56Z INF |  https://obtained-magnificent-cups-enemies.trycloudflare.com                               |
2026-10-06T10:20:56Z INF +--------------------------------------------------------------------------------------------+
2026-10-06T10:20:56Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-10-06T10:20:56Z INF Version 2026.10.0 (Checksum d33ff2d14475178d2012c2c56beba87389ac5ded27649519f198a7d3134a99db)
2026-10-06T10:20:56Z INF GOOS: linux, GOVersion: go1.26.8, GoArch: amd64
2026-10-06T10:20:56Z INF Settings: map[ha-connections:1 no-autoupdate:true protocol:quic url:http://localhost:8501]
2026-10-06T10:20:56Z INF cloudflared will not automatically update if installed by a package manager.
2026-10-06T10:20:56Z INF Generated Connector ID: 67443c5d-d47b-45b3-9684-27c48e73a913
2026-10-06T10:20:56Z INF Initial protocol quic
2026-10-06T10:20:56Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-10-06T10:20:56Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-10-06T10:20:56Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-10-06T10:20:56Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-10-06T10:20:56Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026-10-06T10:20:56Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] connIndex=0 event=0 ip=198.41.200.63
2026/10/06 10:20:56 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-10-06T10:20:56Z INF Registered tunnel connection connIndex=0 connection=5cbb06dd-cd78-4e42-9bea-1b7e91e49a09 event=0 ip=198.41.200.63 location=sea09 protocol=quic
2026-10-06T10:21:02Z INF +-------------------------------------------------------------------------------------+
2026-10-06T10:21:02Z INF |                               CONNECTIVITY PRE-CHECKS                               |
2026-10-06T10:21:02Z INF +-------------------------------------------------------------------------------------+
2026-10-06T10:21:02Z INF |  COMPONENT         TARGET                     STATUS  DETAILS                       |
2026-10-06T10:21:02Z INF |  DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-10-06T10:21:02Z INF |  DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-10-06T10:21:02Z INF |  UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-10-06T10:21:02Z INF |  UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-10-06T10:21:02Z INF |  TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-10-06T10:21:02Z INF |  TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-10-06T10:21:02Z INF |  Cloudflare API    api.cloudflare.com:443     PASS    API is reachable              |
2026-10-06T10:21:02Z INF |                                                                                     |
2026-10-06T10:21:02Z INF |  SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.  |
2026-10-06T10:21:02Z INF +-------------------------------------------------------------------------------------+
2026-10-06T10:21:02Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=08d0d6ef-d36b-4ce5-ae26-30a6e5568499 status=pass target=region1.v2.argotunnel.com
2026-10-06T10:21:02Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=08d0d6ef-d36b-4ce5-ae26-30a6e5568499 status=pass target=region2.v2.argotunnel.com
2026-10-06T10:21:02Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=08d0d6ef-d36b-4ce5-ae26-30a6e5568499 status=pass target=region1.v2.argotunnel.com
2026-10-06T10:21:02Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=08d0d6ef-d36b-4ce5-ae26-30a6e5568499 status=pass target=region2.v2.argotunnel.com
2026-10-06T10:21:02Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=08d0d6ef-d36b-4ce5-ae26-30a6e5568499 status=pass target=region1.v2.argotunnel.com
2026-10-06T10:21:02Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=08d0d6ef-d36b-4ce5-ae26-30a6e5568499 status=pass target=region2.v2.argotunnel.com
2026-10-06T10:21:02Z INF precheck component="Cloudflare API" details="API is reachable" run_id=08d0d6ef-d36b-4ce5-ae26-30a6e5568499 status=pass target=api.cloudflare.com:443
2026-10-06T10:21:02Z INF precheck complete hard_fail=false run_id=08d0d6ef-d36b-4ce5-ae26-30a6e5568499 suggested_protocol=quic
2026-10-06T10:23:17Z INF Initiating graceful shutdown due to signal interrupt ...
2026-10-06T10:23:17Z INF Retrying connection in up to 2s connIndex=0 event=0 ip=198.41.200.63
2026-10-06T10:23:17Z ERR Connection terminated connIndex=0
2026-10-06T10:23:17Z ERR no more connections active and exiting
2026-10-06T10:23:17Z INF Tunnel server stopped
2026-10-06T10:23:17Z INF Metrics server stopped

In [22]:
!streamlit run app.py \
  --server.address=0.0.0.0 \
  --server.port=8501 \
  --server.headless=true

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-10-06 10:23:22.941 Uvicorn server started on 0.0.0.0:8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.169.129.149:8501

  Stopping...
  Stopping...